import { GET_HOUSES, GET_HOUSE_BY_ID, IS_DUPLICATED } from "./queries"
import { ADD_HOUSE, EDIT_HOUSE, DISABLE_HOUSE } from './mutations'

export {
  GET_HOUSES,
  GET_HOUSE_BY_ID,
  IS_DUPLICATED,

  ADD_HOUSE,
  EDIT_HOUSE,
  DISABLE_HOUSE
}